spring.application.name=Saa-16
server.port=8016
# ????????
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# spring ai alibaba config
spring.ai.dashscope.api-key=${DASHSCOPE_API_KEY}
# mcp-client config
spring.ai.mcp.client.request-timeout=20s
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.stdio.servers-configuration=classpath:/mcp-server.json5
