spring.application.name=Saa-17
server.port=8017
# ????????
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# spring ai alibaba config
spring.ai.dashscope.api-key=${DASHSCOPE_API_KEY}