spring.application.name=Saa-18
server.port=8018
# ????????
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# spring ai alibaba config
spring.ai.dashscope.api-key=${DASHSCOPE_API_KEY}
# SAA platForm today`s menu Agent app-id
spring.ai.dashscope.agent.options.app-id=079a4368e69e4291a6e5eabbed17b330